/*
 * GUI_application.java
 *
 * Created on 29 июня 2007 г., 15:10
 */

package java_gui_example;

/**
 *
 * @author  В.В.Монахов
 */
import javax.swing.*;
import java.awt.*;

public class GUI_application extends javax.swing.JFrame {
    /**
     * Creates new form GUI_application
     */
    public GUI_application() {
        try{
            UIManager.setLookAndFeel( UIManager.getSystemLookAndFeelClassName() );
        }catch(Exception e){};
        
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(new Point( (screenSize.width-frameSize.width)/2,
                (screenSize.height-frameSize.width)/2 )
                );
        
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        menuBar1 = new javax.swing.JMenuBar();
        fileMenu1 = new javax.swing.JMenu();
        openMenuItem1 = new javax.swing.JMenuItem();
        saveMenuItem1 = new javax.swing.JMenuItem();
        saveAsMenuItem1 = new javax.swing.JMenuItem();
        exitMenuItem1 = new javax.swing.JMenuItem();
        editMenu1 = new javax.swing.JMenu();
        cutMenuItem1 = new javax.swing.JMenuItem();
        copyMenuItem1 = new javax.swing.JMenuItem();
        pasteMenuItem1 = new javax.swing.JMenuItem();
        deleteMenuItem1 = new javax.swing.JMenuItem();
        helpMenu1 = new javax.swing.JMenu();
        contentsMenuItem1 = new javax.swing.JMenuItem();
        aboutMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GUI Application");
        setBounds(new java.awt.Rectangle(0, 0, 320, 280));
        setMinimumSize(new java.awt.Dimension(350, 240));
        getContentPane().setLayout(null);

        jButton1.setMnemonic('q');
        jButton1.setText("OK");
        jButton1.setToolTipText("<html>\u042d\u0442\u043e - \u043a\u043d\u043e\u043f\u043a\u0430 \u0432\u044b\u0445\u043e\u0434\u0430 \u0438\u0437 \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u044b.<br>\n\u041f\u0440\u0438 \u0435\u0451 \u043d\u0430\u0436\u0430\u0442\u0438\u0438 \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0430 \u0437\u0430\u0432\u0435\u0440\u0448\u0438\u0442 \u0440\u0430\u0431\u043e\u0442\u0443.");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 150, 110, 23);

        jLabel1.setText("\u0418\u043c\u044f:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 23, 14);

        jButton2.setText("\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e");
        getContentPane().add(jButton2);
        jButton2.setBounds(190, 120, 110, 23);

        jLabel2.setText("\u0424\u0430\u043c\u0438\u043b\u0438\u044f:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 40, 48, 14);

        jTextField1.setText("\u0412\u0430\u0434\u0438\u043c");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(60, 10, 70, 20);

        jTextField2.setText("\u041c\u043e\u043d\u0430\u0445\u043e\u0432");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(60, 40, 70, 20);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jCheckBox2.setText("\u041b\u0438\u0440\u0438\u043a");
        jCheckBox2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(10, 40, 49, 15);

        jCheckBox3.setText("\u041f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0438\u0441\u0442");
        jCheckBox3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel1.add(jCheckBox3);
        jCheckBox3.setBounds(10, 60, 83, 15);

        jCheckBox1.setText("\u0424\u0438\u0437\u0438\u043a");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(10, 20, 49, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("\u041f\u0440\u043e\u0444\u0435\u0441\u0441\u0438\u044f");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 0, 63, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(190, 10, 110, 80);

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(null);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("\u041d\u0440\u0430\u0432\u0438\u0442\u0441\u044f");
        jRadioButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel2.add(jRadioButton1);
        jRadioButton1.setBounds(10, 20, 110, 20);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("\u041d\u0435 \u043d\u0440\u0430\u0432\u0438\u0442\u0441\u044f");
        jRadioButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel2.add(jRadioButton2);
        jRadioButton2.setBounds(10, 40, 110, 20);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("\u0423\u0434\u043e\u0432\u043b\u0435\u0442\u0432\u043e\u0440\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0439");
        jRadioButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel2.add(jRadioButton3);
        jRadioButton3.setBounds(10, 60, 129, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("\u0418\u043d\u0442\u0435\u0440\u0444\u0435\u0439\u0441 \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u044b");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 0, 134, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 80, 160, 90);

        fileMenu1.setText("\u0424\u0430\u0439\u043b");

        openMenuItem1.setText("\u041e\u0442\u043a\u0440\u044b\u0442\u044c...");
        openMenuItem1.setActionCommand("Open");
        fileMenu1.add(openMenuItem1);

        saveMenuItem1.setText("\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c");
        saveMenuItem1.setActionCommand("Save");
        fileMenu1.add(saveMenuItem1);

        saveAsMenuItem1.setText("\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c \u043a\u0430\u043a ...");
        saveAsMenuItem1.setActionCommand("Save As ...");
        fileMenu1.add(saveAsMenuItem1);

        exitMenuItem1.setText("\u0412\u044b\u0445\u043e\u0434");
        exitMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu1.add(exitMenuItem1);

        menuBar1.add(fileMenu1);

        editMenu1.setText("\u041f\u0440\u0430\u0432\u043a\u0430");

        cutMenuItem1.setText("\u0412\u044b\u0440\u0435\u0437\u0430\u0442\u044c");
        editMenu1.add(cutMenuItem1);

        copyMenuItem1.setText("\u041a\u043e\u043f\u0438\u0440\u043e\u0432\u0430\u0442\u044c");
        editMenu1.add(copyMenuItem1);

        pasteMenuItem1.setText("\u0412\u0441\u0442\u0430\u0432\u0438\u0442\u044c");
        editMenu1.add(pasteMenuItem1);

        deleteMenuItem1.setText("\u0423\u0434\u0430\u043b\u0438\u0442\u044c");
        editMenu1.add(deleteMenuItem1);

        menuBar1.add(editMenu1);

        helpMenu1.setText("\u0421\u043f\u0440\u0430\u0432\u043a\u0430");

        contentsMenuItem1.setText("\u0421\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u0435");
        helpMenu1.add(contentsMenuItem1);

        aboutMenuItem1.setText("\u041e \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0435");
        helpMenu1.add(aboutMenuItem1);

        menuBar1.add(helpMenu1);

        setJMenuBar(menuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    System.exit(0);
}//GEN-LAST:event_jButton1ActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_application().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem contentsMenuItem1;
    private javax.swing.JMenuItem copyMenuItem1;
    private javax.swing.JMenuItem cutMenuItem1;
    private javax.swing.JMenuItem deleteMenuItem1;
    private javax.swing.JMenu editMenu1;
    private javax.swing.JMenuItem exitMenuItem1;
    private javax.swing.JMenu fileMenu1;
    private javax.swing.JMenu helpMenu1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JMenuBar menuBar1;
    private javax.swing.JMenuItem openMenuItem1;
    private javax.swing.JMenuItem pasteMenuItem1;
    private javax.swing.JMenuItem saveAsMenuItem1;
    private javax.swing.JMenuItem saveMenuItem1;
    // End of variables declaration//GEN-END:variables
    
}
