/*
 * AdditionalClass.java
 *
 * Created on 4 РёСЋР»СЏ 2007 Рі., 13:44
 *
 * To change this template, choose Tools | Template Manager
 * and open the template in the editor.
 */

package java_enum_pkg;
/**
 * java_enum_pkg
 * Пример документационных комментариев для пакета <b>java_enum_pkg</b>
 */
import pckg1.*;

/*
import java.awt.Toolkit;
import java.awt.Dimension;
import java.awt.Point;
 */


enum Months {jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec};
enum Spring {march,apr,may};

class EnumWrapper {
 AdditionalClass addObj;
 public Spring m; 
 private int p=0;
 public int getP(){
    return  p;
 }
 
 public EnumWrapper(){  
     addObj=new AdditionalClass();
 }
}

class EnumWrapper1 extends  EnumWrapper{
 public Spring m; 
 int p=1;
 
 public int getP(){
    return  p;
 }
  
 public EnumWrapper1(){    
 }
}

/**
 * Пример приложения Java с документационными комментариями 
 * В приложении заданы типы-перечисления Months и Spring и показано, как с ними работать.
 * @see enumApplication.Months Информация о типе-перечислении Months
 * @see enumApplication.Spring
 * @see enumApplication#m1
 * @version 0.2 для среды NetBeans 6.0 
 * @author Вадим Валериевич Монахов
 */

public class enumApplication extends javax.swing.JFrame {
    //public EnumWrapper enumWrapper1,enumWrapper2;
    int i=1;
    int jan=1;
    
/**
  * Spring - задаёт перечисление из 3 весенних месяцев года: march,apr,may. 
  *  <ul>
  *   <li>march
  *   <li>apr
  *   <li>may
  *  </ul>
  * Идентификатор для марта записан отличающимся от соответствующего идентификатора
  * в перечислении Months, а для апреля и мая записаны так же - чтобы подчеркнуть,
  * что их пространства имён независимы.
  */
    public enum Spring {march,apr,may};
 
    /**
     * Months - задаёт перечисление из 12 месяцев года: <br>
     * jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec
     * (январь, февраль и т.д.)
     */

    public enum Months {jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec};
    Spring spr1= Spring.apr, spr2;
    
    /**
     * Переменная, иллюстрирующая работу с перечислениями
     */
    public Months m1,m2=Months.mar,m3;
    public boolean b;
    byte i1=5,i2=-5;
    /**
     * Creates new form enumApplication
     */
    public enumApplication() {
        initComponents();
        //this.setLocation(300,200);
        /* Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(new Point((screenSize.width - frameSize.width) / 2,
                              (screenSize.height - frameSize.width) / 2));
         */
    }
    
   
    public void setEnumSpring_march(Spring m){
     Months m1,m2=Months.mar,m2a; 
     Spring m3,m4;
     m=Spring.march;
     m3=m;
     m4=m;
     System.out.println("m="+m+" m3="+m3+" m4="+m4);
     m=Spring.apr;
     System.out.println("m="+m+" m3="+m3+" m4="+m4);
    }
    
    public void setEnumFeb(Spring m,boolean b){
     m=Spring.apr;
     b=true;
    }
    
    @SuppressWarnings({"empty-statement", "empty-statement"})
    public void showEnum(Spring m){
     if(b=true){};
     if(i==Math.pow(1.5,3)){}
     System.out.println("month="+m+" bool="+b);   
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("\u041f\u0440\u0438\u043c\u0435\u0440 vm1");
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel1.setText("\u041f\u0440\u0438\u0432\u0435\u0442!");

        jButton2.setText("spr2.compareTo(...)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("setEnum feb");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u044f");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("setEnum jan");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("m1=?");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton9.setText("new enumWrapper1");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton11.setText("null.data");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        fileMenu.setText("File");
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setText("Save As ...");
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });

        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setText("Edit");
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setText("Help");
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jButton6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jButton3, 0, 0, Short.MAX_VALUE)
                            .add(jButton5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(91, 91, 91)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jButton4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jButton2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .add(layout.createSequentialGroup()
                        .add(jButton9)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButton11)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton2)
                    .add(jButton5))
                .add(6, 6, 6)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton3)
                    .add(jButton4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton6)
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton1))
                .add(27, 27, 27)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton9)
                    .add(jButton11))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    EnumWrapper enumWrapper;
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
      System.out.println("enumWrapper.m="+enumWrapper.m);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        EnumWrapper enumWrapper;
        EnumWrapper1 enumWrapper1;
        enumWrapper=new EnumWrapper1();
        enumWrapper1=new EnumWrapper1();
        System.out.println("enumWrapper.getP()="+enumWrapper.getP());
        System.out.println("enumWrapper1.getP()="+enumWrapper1.getP()); 
        AdditionalClass a1;
   
                      
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
// m1=?
        System.out.println("m1: month="+spr1);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     //setEnum jan m1
        setEnumSpring_march(spr1);
       System.out.println("setEnumJan month="+spr1);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
        //false length equals Enumeration

        long   i=5,j=600000000000000L,k;
        char c1,c2,c3;
        j=j+'a'*'a'+1000/'b' ;
        c1='a';
        c2=63;//97;
        c3=64;//'\u0061';
        System.out.println("i1="+i1+" i2="+i2);
        i=2*c2/c1;
        j=-5/4;
        //j=c1+c2;
        System.out.println("i="+i+" j="+j);
        System.out.println("c1="+c1+" c2="+c2+" c3="+c3);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//setEnum feb m1
    setEnumFeb(spr1,b); 
    System.out.println("setEnumFeb month="+spr1+" bool="+b);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
           //spr2=spr1;
           int i=1;
	   spr1=Spring.may;
           spr1=Spring.values()[i];
           System.out.println("spr1="+spr1);
           System.out.println("spr2="+spr2
                   //+spr2.name()+
                   //" spr2.ordinal())="+spr2.ordinal()
                   );
         //  System.out.println("пїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅ пїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅ="+spr2.compareTo(Spring.march)+
          //         " spr1.ordinal())="+spr1.ordinal());

   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
       System.exit(0);   
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new enumApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables
    
}



