/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnipackage_Multiply */

#ifndef _Included_jnipackage_Multiply
#define _Included_jnipackage_Multiply
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnipackage_Multiply
 * Method:    getJniProduct
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_jnipackage_Multiply_getJniProduct
  (JNIEnv *, jclass, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
