/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example_Multiply */

#ifndef _Included_example_Multiply
#define _Included_example_Multiply
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example_Multiply
 * Method:    getProduct
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_example_Multiply_getProduct__DD
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     example_Multiply
 * Method:    getProduct
 * Signature: ([[D[[D)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_example_Multiply_getProduct___3_3D_3_3D
  (JNIEnv *, jclass, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
